### ISSUE TITLE
Domain redirection with params.

### ISSUE THREAD

**Issue by leadingproperties** [gbuesing/rack-host-redirect#1]
Hi
Im using this example

`config.middleware.use Rack::HostRedirect, {
  'bar.myapp.com' => {host: 'www.myapp.com', path: '/', query: nil}
}`

to redirect **domain.foo => domain.bar/foo.**
All working fine except that I cannot pass links here. as example

**domain.foo/test => domain.bar/foo** (/test missing)

Can I do something like this

**domain.foo/test => domain.bar/foo/test** ?

**Comment by gbuesing** [comment]
You can't currently do that.

Are you looking to redirect any request coming to to `domain.foo`, or only requests to `domain.foo/test`?

I've thought of adding a feature to handle a `:path_prefix` key in the uri options hash, so that I could redirect requests from a subdomain to a url namespace, while preserving the original request path -- maybe that would handle your need as well?

**Comment by leadingproperties** [comment]
need to redirect all from domain.foo to domain.bar/foo
as example 
domain.foo/test-link => domain.bar/foo/test-link
domain.foo/example-link/test-link => domain.bar/foo/example-link/test-link

**Comment by gbuesing** [comment]
Ok good I think we're talking about the same requirement. So, proposed api for your example would be:

``` ruby
config.middleware.use Rack::HostRedirect, {
  'domain.foo' => {host: 'domain.bar', path_prefix: 'foo'}
}
```

...and the middleware would just prepend the path_prefix to the request path to build the redirect link.

If you're so inclined, please feel free to put together a pull request, and I'd be happy to merge it in.
