### ISSUE TITLE
Feature request: skip redirection on certain routes

### ISSUE THREAD

**Issue by worldlywisdom** [gbuesing/rack-host-redirect#2]
Thanks for creating this gem - it's very useful!

I'm wondering if it's possible to add a feature to skip redirection on certain routes.

Here's the use case: I'm using Let's Encrypt (https://letsencrypt.org) for automated SSL encryption. The LE http-01 method of requires verification of a challenge/response on each requested domain before issuing certificates. I'm trying to automatically issue certificates on `example.com` and `www.example.com`.

I'm currently using `rack-host-redirect` to strip `www` from all requests:

```
use Rack::HostRedirect, {
    'www.example.com' => 'example.com'
}
```

When LE verification attempts to verify the response at `www.example.com/.well-known/acme-challenge/*` (where `*` is the challenge string), verification fails because of the 301 redirect, even though the server provides the correct response after the redirect.

Is there a straightforward way to add a feature that will allow skipping redirection on requests on a route like `www.example.com/.well-known/acme-challenge/*` so verification can pass?

Thanks for considering, and happy to help however I can. (I'm reading the code now, but I'm not familiar enough with Rack to contribute a pull request yet...)

**Comment by worldlywisdom** [comment]
Update: adding the following mapping in `config.ru` before `use Rack::HostRedirect` works:

```
### Let's Encrypt verification
map "/.well-known/acme-challenge/#{ENV['SSL_CHALLENGE_TOKEN']}" do
  run Proc.new { |env| ['200', {'Content-Type' => 'text/plain'}, "#{ENV['SSL_CHALLENGE_RESPONSE']}"] }
end
```

(Assuming, of course, you set the Let's Encrypt challenge/response as `ENV` variables.)

**Comment by gbuesing** [comment]
Glad this worked for you -- seems simpler to do this up the middleware stack like you're doing vs. adding blacklist/skip logic to RackHost::Redirect.

**Comment by halo** [comment]
I'm facing the same problem. I'm using a [third party](https://github.com/lgromanowski/letsencrypt-plugin/blob/6d22ebde9f246694c90ba09b80ee507abe45985a/lib/letsencrypt_plugin/engine.rb#L2) gem which requires the request to go all the way through the middleware up into the application layer.

I don't think I can work around this other than building my own host-redirect middleware which lets those requests pass through. Alternatively, @lgromanowski might move the plugin down into the rack stack :)

It would be nice if `Rack::HostRedirect` would have a configuration option similar to [how Rails does](https://github.com/rails/rails/blob/93982de132f5e3fdcd7794d697a6566bd98da393/actionpack/lib/action_dispatch/middleware/ssl.rb#L71) it:

```ruby
class Application < Rails::Application
  config.ssl_options = {
    redirect: { exclude: ->(request) { request.path == '/may/be/accessed/without/ssl' } }
  }
end
```

**Comment by gbuesing** [comment]
What about using another solution that's implemented in middleware, e.g.: 

https://github.com/pixielabs/letsencrypt-rails-heroku
https://github.com/xijo/letsencrypt_rack

You could just add one of those to the Rack stack ahead of Rack::HostRedirect.

**Comment by halo** [comment]
Thank you for the hint, I was not aware of those. Some with a very minimalistic, smart approach!

As it stands, I'll continue to use the one I have and locally modify the `HostRedirect` middleware instead. That's because of some implementation details I found in the gems you mentioned:

* I dislike having to restart my application multiple times in a very short time interval
* I have CloudFront before Heroku so I don't want the certificate to be uploaded on-the-fly to Heroku only, but also to AWS
* Having multiple webservers, it's not feasible to store the challenge on disk

So far, the plugin I'm using saves me the headache of those points. But I'll reconsider periodically thanks to you! :) Or at least I should suggest PRs for those rack based gems :)

I agree with you that this redirect issue should be avoided altogether, if possible.

**Comment by gbuesing** [comment]
Gotcha. I haven't used Let's Encrypt, so I'm not aware of these considerations, but makes sense.

Wonder if we could come up with a decent declarative API for this, e.g.:

```ruby
config.middleware.use Rack::HostRedirect, {
  'www.example.com' => {host: 'example.com', allow_acme_challenge: true}
}
```

On the fence about this. Thoughts?

**Comment by halo** [comment]
I think that `Rack::HostRedirect` is a very very general middleware that should not be entangled with anything that has to do with letsencrypt specifically. So I recommend against some flag called `allow_acme` because once you're finished with that, you'll have someone come along who has another third party tool and another and another.

It's quite common in Rails routes to define exceptions based on the request object and a proc. I think that's a sensible (and rather conventional) way to cover pretty much all use cases.

It's fairly easy to implement. You can see that [here](https://github.com/rails/rails/blob/93982de132f5e3fdcd7794d697a6566bd98da393/actionpack/lib/action_dispatch/middleware/ssl.rb#L56) is a default proc, something like this

```ruby
# default is "false" as in "do not exclude anything"
@exclude_proc = @options[:exclude] || proc { false }
```

Then your middleware [only kicks in](https://github.com/rails/rails/blob/93982de132f5e3fdcd7794d697a6566bd98da393/actionpack/lib/action_dispatch/middleware/ssl.rb#L71) when the proc evaluates to true, something like this:

```ruby
# If there is no exclusion, go ahead and handle the request in your middleware
return do_whatever_rack_host_redirect_does(request) unless @exclude_proc.call(request)
# At this point we know there is an exclusion and we pass the request up the stack
@app.call(env)
```

That being said I should just have created a PR 😃

**Comment by gbuesing** [comment]
@halo Good point about leaving this middleware generic. I'm coming around to your initial suggestion of passing in an ```:exclude``` Proc for this 😄 

I went ahead and pulled together a pull request https://github.com/gbuesing/rack-host-redirect/pull/3

Usage example:

```ruby
# Allow ACME challenge request to pass through, redirect everything else:
config.middleware.use Rack::HostRedirect, {
  'www.example.com' => {
    host: 'example.com', 
    exclude: -> (request) { request.path.start_with?('/.well-known/acme-challenge/') }
  }
}
```

I think it's pretty easy to see what's going on there. And under the hood, code is still pretty simple.

Thank you for arguing the case for this! If you get a chance, please do pull this in to your app and confirm this is working as expected. If it is, I'd be happy to push out a gem release.

**Comment by gbuesing** [comment]
Gem version 1.3.0 was just pushed with new ```:exclude``` feature. Thanks for your help, @halo !
